build: off

branches:
  only:
    - master

skip_branch_with_pr: true

environment:
  matrix:
  - TOXENV: py37
  - TOXENV: py38
  - TOXENV: py39
    
install:
  - py -m pip install tox

test_script:
  - py -m tox
